name: es-experiment
version: 1.0.0


default-extensions:
  - DeriveGeneric
  - FlexibleInstances
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards


dependencies:
  - aeson == 1.2.*
  - aeson-pretty == 0.8.*
  - base >= 4.7 && < 5
  - dhall == 1.11.*
  - directory == 1.3.*
  - filepath == 1.4.*
  - flow == 1.0.*
  - postgresql-simple == 0.5.*
  - protolude == 0.2.*
  - shikensu == 0.3.*
  - text == 1.2.*


executables:
  # 🚜
  assess_system:
    main: Main.hs
    source-dirs:
      - lib
      - system/Assessment
