name: es-experiment
version: 1.0.0


default-extensions:
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleInstances
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables


dependencies:
  - aeson == 1.2.*
  - aeson-pretty == 0.8.*
  - base >= 4.7 && < 5
  - bytestring
  - cryptohash-md5 == 0.11.*
  - dhall == 1.11.*
  - directory == 1.3.*
  - filepath == 1.4.*
  - flow == 1.0.*
  - hedis == 0.10.*
  - postgresql-simple == 0.5.*
  - protolude == 0.2.*
  - safe-exceptions == 0.1.*
  - scotty == 0.11.*
  - shikensu == 0.3.*
  - text == 1.2.*
  - unordered-containers == 0.2.*
  - unix-time == 0.3.*


executables:
  # âš™ï¸
  assess_system:
    main: Assess.hs
    source-dirs:
      - lib
      - system/Assessment

  # ðŸ“±
  boot_app:
    main: App.hs
    source-dirs:
      - app
      - lib

  # ðŸŒ’
  replay:
    main: Replay.hs
    source-dirs:
      - lib
      - system/Replaying
